# 代码检查

name: build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - '!*.md'
    - '!.github/workflows/**.'
    - '!LICENSE'
    branches-ignore:
      - release
    tags-ignore:
      - 'v*'
  pull_request:
#    branches: [main]
    paths:
    - '**.cs'
    - '**.csproj'
    branches-ignore:
      - release
    tags-ignore:
      - 'v*'

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]


    steps:
      - uses: actions/checkout@v2
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
