# 版本发布
## 这里先提交tag版本时进行发布，待增加release功能后换成release来发布nuget package

name: release

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        id: publish_nuget
        uses: rohith/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/DotNet/DotNet.csproj
          NUGET_KEY: ${{secrets.NUGET_API_SECRET}}
          NUGET_SOURCE: https://api.nuget.org/v3
          TAG_FORMAT: v*
          PACKAGE_NAME: DotNet
